# NumPy

## NumPy Arrays

In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [7]:
my_matrix = [
    [1 ,2, 3],
    [4 ,5, 6],
    [7, 8, 9]
]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.linspace(0, 5, 6)

array([0., 1., 2., 3., 4., 5.])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(1)

array([0.00553338])

In [21]:
np.random.rand(5,2)

array([[0.56415926, 0.9878994 ],
       [0.6434605 , 0.31847899],
       [0.78732043, 0.75859734],
       [0.05958728, 0.66813554],
       [0.99186977, 0.3422575 ]])

In [22]:
np.random.randn(10)

array([ 1.62726296,  0.47761105,  1.21179761,  0.37194161, -0.93931131,
        0.43107425,  1.47124377, -0.05394822,  0.10463569,  0.76002615])

In [23]:
np.random.randn(2,3)

array([[ 0.11506332, -0.03760794, -1.49638715],
       [ 1.30300797, -1.36034517,  1.80407421]])

In [24]:
np.random.randint(0, 101, 5)

array([86, 20, 16, 43, 20])

In [25]:
np.random.randint(0, 101, (4,5))

array([[34, 87, 58, 55, 33],
       [55, 73, 76, 34, 45],
       [42,  9, 84, 21, 82],
       [48, 94, 72, 26, 42]])

In [26]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [27]:
arr = np.arange(0, 25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
randarr = np.random.randint(0, 101, 10)

In [31]:
randarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [32]:
randarr.max()

99

In [33]:
randarr.min()

2

In [34]:
# returns index position of max num
randarr.argmax()

5

In [35]:
# returns index position of min num
randarr.argmin()

7

In [36]:
randarr.dtype

dtype('int64')

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr.shape

(25,)

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## NumPy Indexing and Selection

In [40]:
arr = np.arange(0,11, 1)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[8]

8

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# broadcast 100 over the range
arr[0:5] = 100

In [49]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr = np.arange(0,11)

In [51]:
slice_of_arr = arr[0:5]

In [52]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [53]:
slice_of_arr[:] = 99

In [54]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [56]:
arr_copy = arr.copy()

In [57]:
arr_copy[:] = 100

In [58]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [60]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [61]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d.shape

(3, 3)

In [63]:
arr_2d[0]

array([ 5, 10, 15])

In [64]:
arr_2d[2]

array([35, 40, 45])

In [65]:
arr_2d[1,1]

25

In [66]:
arr_2d[0,2]

15

In [67]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [69]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [70]:
arr = np.arange(1,11)

In [71]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [72]:
bool_arr = arr > 4

In [73]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [74]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [75]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

## NumPy Operations

In [77]:
arr = np.arange(0,10)

In [78]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# adds 5 to eac h element in the array
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [81]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [83]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
1 / 0

ZeroDivisionError: division by zero

In [87]:
1 / arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [88]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [89]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [90]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [91]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
arr.sum()

45

In [93]:
arr.mean()

4.5

In [94]:
arr.max()

9

In [95]:
arr.var()

8.25

In [96]:
arr.std()

2.8722813232690143

In [98]:
arr2d = np.arange(0, 25).reshape(5,5)

In [99]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
arr2d.sum()

300

In [101]:
# perform a sum across each row (sum of the individual columns)
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [102]:
# perform a sum across each column (sum of the individual rows)
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])